model_path:
  small: "./models/mistral-7b-instruct-v0.1.Q5_K_M.gguf"
  large: "./models/mistral-7b-instruct-v0.2.Q5_K_M.gguf"
  phi_turkish: "./models/phi-2-chat-turkish.fp16.gguf"
  phi_two: "./models/phi-2.Q5_K_M.gguf"
  mistral_turkish: "malhajar/Mistral-7B-Instruct-v0.2-turkish"
  llama2_finetuned: "./models/trendyol-llm-7b-chat-v0.1.Q5_K_M.gguf"
  mistral_finetuned: ""./models/trendyol-llm-7b-chat-v1.0.Q5_K_S.gguf"

model_type: "mistral"

embeddings_path: "./embedding_model/hkunlp_instructor-xl"
#embeddings_path: "BAAI/bge-large-en-v1.5"

model_config: { 'max_new_tokens': 512 , 'temperature': 0.1 ,'context_length': 4096,  'gpu_layers' : 0 }

chat_history_path: "./chat_sessions/"
